import type { Metadata } from 'next';
import Link from 'next/link';
import SiteHeader from '@/components/SiteHeader';
import SiteFooter from '@/components/SiteFooter';
import { LISTICLE_PAGES, BRAND_INFO } from './data';

export const metadata: Metadata = {
  title: 'Best Software Alternatives Guide 2026 | SEOPages.pro',
  description: 'Find the best alternatives to popular software tools. Expert-tested comparisons of AI writers, SEO tools, and more. Updated for 2026.',
  keywords: ['software alternatives', 'best alternatives', 'tool comparisons', 'AI writing tools', 'SEO tools'],
  openGraph: {
    title: 'Best Software Alternatives Guide 2026',
    description: 'Find the best alternatives to popular software tools. Expert-tested comparisons.',
    url: 'https://seopages.pro/best-alternatives',
    type: 'website',
    images: [
      {
        url: 'https://seopages.pro/new-logo.png',
        width: 512,
        height: 512,
        alt: 'Best Software Alternatives',
      },
    ],
  },
  alternates: {
    canonical: 'https://seopages.pro/best-alternatives',
  },
};

// Favicon helper
function getFaviconUrl(domain: string, size: number = 64): string {
  return `https://www.google.com/s2/favicons?domain=${domain}&sz=${size}`;
}

export default function BestAlternativesHubPage() {
  return (
    <div className="min-h-screen bg-[#0A0A0A] text-white">
      <SiteHeader />
      
      {/* Hero Section */}
      <section className="pt-32 pb-16 px-4 sm:px-6">
        <div className="max-w-6xl mx-auto text-center">
          {/* "We Built This" Badge */}
          <div className="inline-flex items-center gap-3 px-4 py-2 bg-gradient-to-r from-[#FFAF40]/20 via-[#9A8FEA]/20 to-[#65B4FF]/20 border border-[#9A8FEA]/30 rounded-full mb-6">
            <span className="flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-2 w-2 rounded-full bg-green-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-green-500"></span>
            </span>
            <span className="text-sm font-medium text-white">{LISTICLE_PAGES.length} Listicles · 100% AI-Generated · Built with SEOPages.pro</span>
          </div>
          
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold mb-6">
            <span className="text-white">{LISTICLE_PAGES.length} Listicle Pages.</span>
            <br />
            <span className="bg-gradient-to-r from-[#FFAF40] via-[#D194EC] to-[#65B4FF] bg-clip-text text-transparent">
              All Built in Minutes.
            </span>
          </h1>
          
          <p className="text-xl text-gray-400 max-w-3xl mx-auto mb-4">
            Every &quot;Best Alternatives&quot; guide below was <span className="text-white font-medium">generated by SEOPages.pro</span>. 
            No copywriters. No research team. Just AI magic.
          </p>
          <p className="text-lg text-[#9A8FEA] max-w-2xl mx-auto mb-8">
            Your product deserves the same. Get started in 60 seconds. 🚀
          </p>
          
          <div className="flex flex-wrap justify-center gap-4 mb-12">
            <Link
              href={BRAND_INFO.ctaUrl}
              className="group px-6 py-3 bg-gradient-to-r from-[#FFAF40] via-[#9A8FEA] to-[#65B4FF] text-white font-semibold rounded-xl hover:opacity-90 transition-all flex items-center gap-2"
            >
              Build Your Listicle Pages
              <svg className="w-4 h-4 group-hover:translate-x-1 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
              </svg>
            </Link>
            <a
              href="#guides"
              className="px-6 py-3 bg-white/10 text-white font-semibold rounded-xl hover:bg-white/20 transition-all border border-white/20"
            >
              Browse All {LISTICLE_PAGES.length} Guides
            </a>
          </div>
          
          {/* Quick Stats - Emphasize "We Built These" */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 max-w-4xl mx-auto">
            {[
              { stat: `${LISTICLE_PAGES.length}`, label: 'Pages Generated' },
              { stat: '<3min', label: 'Per Listicle' },
              { stat: '$0', label: 'Writers Hired' },
              { stat: '100%', label: 'AI-Powered' },
            ].map((item, idx) => (
              <div key={idx} className="p-4 bg-white/5 border border-white/10 rounded-xl">
                <div className="text-2xl font-bold bg-gradient-to-r from-[#9A8FEA] to-[#65B4FF] bg-clip-text text-transparent">
                  {item.stat}
                </div>
                <div className="text-sm text-gray-400">{item.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>
      
      {/* How We Built These Section */}
      <section className="py-16 px-4 sm:px-6 bg-white/[0.02]">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-2xl sm:text-3xl font-bold text-center mb-4">
            How We Built {LISTICLE_PAGES.length} Listicle Pages
          </h2>
          <p className="text-gray-400 text-center max-w-2xl mx-auto mb-12">
            No research team. No content writers. Just SEOPages.pro doing its thing.
          </p>
          
          <div className="grid md:grid-cols-3 gap-6">
            {[
              {
                icon: (
                  <svg className="w-8 h-8 text-[#FFAF40]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M13 10V3L4 14h7v7l9-11h-7z" />
                  </svg>
                ),
                title: '3 Minutes Per Listicle',
                description: 'Each "Best X Alternatives" guide took ~3 minutes. Manual research and writing? Days.',
              },
              {
                icon: (
                  <svg className="w-8 h-8 text-[#9A8FEA]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                  </svg>
                ),
                title: 'AI-Powered Research',
                description: 'Our AI researches competitors, compares features, and writes compelling content automatically.',
              },
              {
                icon: (
                  <svg className="w-8 h-8 text-[#65B4FF]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
                  </svg>
                ),
                title: 'Rank-Ready Output',
                description: 'SEO-optimized structure, proper schema, and content designed to win featured snippets.',
              },
            ].map((item, idx) => (
              <div key={idx} className="p-6 bg-white/5 border border-white/10 rounded-2xl hover:border-[#9A8FEA]/50 transition-all">
                <div className="mb-4">{item.icon}</div>
                <h3 className="text-lg font-semibold mb-2">{item.title}</h3>
                <p className="text-gray-400 text-sm">{item.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
      
      {/* All Listicle Pages */}
      <section id="guides" className="py-16 px-4 sm:px-6 scroll-mt-20">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-2xl sm:text-3xl font-bold text-center mb-4">
            Best Alternatives Guides
          </h2>
          <p className="text-gray-400 text-center max-w-2xl mx-auto mb-12">
            Click any guide to see the full breakdown with features, pricing, pros & cons.
          </p>
          
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {LISTICLE_PAGES.map((page) => (
              <Link
                key={page.slug}
                href={`/best-alternatives/${page.slug}`}
                className="group p-6 bg-white/5 border border-white/10 rounded-2xl hover:border-[#9A8FEA]/50 hover:bg-white/[0.08] transition-all"
              >
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-12 h-12 rounded-xl bg-white/10 flex items-center justify-center overflow-hidden">
                    <img
                      src={getFaviconUrl(page.targetWebsite, 48)}
                      alt={page.targetProduct}
                      className="w-8 h-8"
                    />
                  </div>
                  <div>
                    <h3 className="font-semibold text-white group-hover:text-[#9A8FEA] transition-colors">
                      Best {page.targetProduct} Alternatives
                    </h3>
                    <span className="text-xs text-gray-500">{page.products.length} alternatives reviewed</span>
                  </div>
                </div>
                
                <p className="text-sm text-gray-400 mb-4 line-clamp-2">
                  {page.heroDescription}
                </p>
                
                {/* Top 3 products preview */}
                <div className="flex items-center gap-1 mb-4">
                  {page.products.slice(0, 4).map((product, idx) => (
                    <div 
                      key={idx}
                      className="w-6 h-6 rounded-md bg-white/10 flex items-center justify-center overflow-hidden -ml-1 first:ml-0 border border-[#0A0A0A]"
                      title={product.name}
                    >
                      <img
                        src={product.logoUrl || getFaviconUrl(product.website, 32)}
                        alt={product.name}
                        className="w-4 h-4"
                      />
                    </div>
                  ))}
                  {page.products.length > 4 && (
                    <span className="text-xs text-gray-500 ml-2">+{page.products.length - 4} more</span>
                  )}
                </div>
                
                <div className="flex items-center justify-between">
                  <span className="text-xs text-[#9A8FEA]">Updated Jan 2026</span>
                  <svg className="w-4 h-4 text-gray-600 group-hover:text-[#9A8FEA] group-hover:translate-x-1 transition-all" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                  </svg>
                </div>
              </Link>
            ))}
          </div>
        </div>
      </section>
      
      {/* CTA Section */}
      <section className="py-20 px-4 sm:px-6">
        <div className="max-w-4xl mx-auto">
          <div className="relative p-8 sm:p-12 bg-gradient-to-br from-[#9A8FEA]/10 to-[#65B4FF]/10 border border-[#9A8FEA]/30 rounded-3xl text-center">
            <div className="absolute -top-3 left-1/2 -translate-x-1/2 px-4 py-1 bg-[#0A0A0A] border border-[#9A8FEA]/50 rounded-full">
              <span className="text-xs text-[#9A8FEA] font-medium">Your Product. Same Quality.</span>
            </div>
            
            <h2 className="text-3xl sm:text-4xl font-bold mb-4">
              Build Listicle Pages Like These
            </h2>
            <p className="text-gray-400 text-lg mb-8 max-w-2xl mx-auto">
              We generated {LISTICLE_PAGES.length} &quot;Best Alternatives&quot; guides with SEOPages.pro. 
              <span className="text-white"> Create yours in minutes, not days.</span>
            </p>
            <Link
              href={BRAND_INFO.ctaUrl}
              className="inline-flex items-center gap-2 px-8 py-4 bg-gradient-to-r from-[#FFAF40] via-[#9A8FEA] to-[#65B4FF] text-white font-semibold rounded-xl hover:opacity-90 transition-all text-lg"
            >
              Generate Your Own Listicles
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
              </svg>
            </Link>
            <p className="text-sm text-gray-500 mt-4">10 pages for $4.9 · One-time payment · SEO-optimized output</p>
          </div>
        </div>
      </section>
      
      <SiteFooter />
    </div>
  );
}
